name: "Template"
description: ""
inputs:
  orgname:
    description: "ex: TickLabVN"
    required: true
  TOKEN:
    description: "secrets.GITHUB_TOKEN"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
  post: "commit.js"
